// src/components/modals/CommandPalette.tsx
import React, { useState, useEffect, useRef } from 'react';
import { 
  Search, 
  X, 
  ArrowRight, 
  Map, 
  BookOpen, 
  Binary, 
  Coffee, 
  Leaf, 
  Layers, 
  Cpu, 
  Bot, 
  Languages, 
  FolderGit2, 
  Flame, 
  Award, 
  BarChart3,
  Repeat
} from 'lucide-react';
import { useLearning } from '../../context/LearningContext';

interface CommandPaletteProps {
  isOpen: boolean;
  onClose: () => void;
  onNavigate: (view: string) => void;
}

export const CommandPalette: React.FC<CommandPaletteProps> = ({ isOpen, onClose, onNavigate }) => {
  const [query, setQuery] = useState('');
  const { knowledgeTopics, dsaProblems, setCurrentDay, roadmapDays } = useLearning();
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && isOpen) {
        onClose();
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isOpen, onClose]);

  useEffect(() => {
    if (isOpen) {
      setTimeout(() => inputRef.current?.focus(), 50);
    } else {
      setQuery('');
    }
  }, [isOpen]);

  if (!isOpen) return null;

  const baseCommands = [
    { id: 'dashboard', label: 'Go to Dashboard', category: 'Navigation', icon: BarChart3, view: 'dashboard' },
    { id: 'today', label: 'Go to Today Mission Control', category: 'Navigation', icon: Map, view: 'today' },
    { id: 'review', label: 'Start Spaced Review (Active Recall)', category: 'Study', icon: Repeat, view: 'review' },
    { id: 'knowledge', label: 'Open Knowledge System & Dimensions', category: 'Knowledge', icon: BookOpen, view: 'knowledge' },
    { id: 'dsa', label: 'DSA Pattern Practice Tracker', category: 'Coding', icon: Binary, view: 'dsa' },
    { id: 'java', label: 'Core Java & Concurrency Module', category: 'Track', icon: Coffee, view: 'java' },
    { id: 'spring', label: 'Spring Boot 3 Deep Dive', category: 'Track', icon: Leaf, view: 'spring' },
    { id: 'microservices', label: 'Microservices, Kafka & Outbox', category: 'Track', icon: Layers, view: 'microservices' },
    { id: 'systemdesign', label: 'System Design Architecture Lab', category: 'Track', icon: Cpu, view: 'systemdesign' },
    { id: 'claudecode', label: 'Claude Code Agent Masterclass', category: 'Track', icon: Bot, view: 'claudecode' },
    { id: 'english', label: 'Technical English Voice Practice', category: 'Track', icon: Languages, view: 'english' },
    { id: 'project', label: 'E-Commerce Platform Services', category: 'Hands-on', icon: FolderGit2, view: 'project' },
    { id: 'incident', label: 'Incident Lab (Break The System)', category: 'Hands-on', icon: Flame, view: 'incident' },
    { id: 'interview', label: 'Senior Interview Mock Simulator', category: 'Assessment', icon: Award, view: 'interview' },
    { id: 'analytics', label: 'Readiness Radar & Analytics', category: 'Assessment', icon: BarChart3, view: 'analytics' },
  ];

  const filteredCommands = baseCommands.filter(c => 
    c.label.toLowerCase().includes(query.toLowerCase()) || 
    c.category.toLowerCase().includes(query.toLowerCase())
  );

  const filteredTopics = knowledgeTopics.filter(t => 
    t.title.toLowerCase().includes(query.toLowerCase()) || 
    t.category.toLowerCase().includes(query.toLowerCase())
  ).slice(0, 5);

  const filteredDSA = dsaProblems.filter(p => 
    p.title.toLowerCase().includes(query.toLowerCase()) || 
    p.pattern.toLowerCase().includes(query.toLowerCase())
  ).slice(0, 4);

  // Check if query is a day number e.g. "day 45" or "37"
  const dayMatch = query.match(/(?:day\s*)?(\d+)/i);
  const matchedDay = dayMatch ? parseInt(dayMatch[1], 10) : null;
  const isValidDay = matchedDay !== null && matchedDay >= 1 && matchedDay <= 180;

  const handleSelect = (view: string) => {
    onNavigate(view);
    onClose();
  };

  const handleJumpDay = (day: number) => {
    setCurrentDay(day);
    onNavigate('today');
    onClose();
  };

  return (
    <div 
      className="fixed inset-0 bg-black/70 backdrop-blur-xs flex items-start justify-center p-4 pt-16 sm:pt-24 z-50 animate-in fade-in duration-150"
      onClick={onClose}
    >
      <div 
        role="dialog"
        aria-modal="true"
        aria-label="Command Palette"
        onClick={(e) => e.stopPropagation()}
        className="w-full max-w-xl bg-[#111622] border border-[#1E293B] rounded-lg shadow-2xl overflow-hidden animate-in zoom-in-95 duration-150"
      >
        {/* Search Input */}
        <div className="p-3 bg-[#0B0E14] border-b border-[#1E293B] flex items-center gap-3">
          <Search className="w-4 h-4 text-[#38BDF8] shrink-0" />
          <input
            ref={inputRef}
            type="text"
            placeholder="Type a command, topic, pattern, or day (e.g. 'Kafka', 'Day 37', 'Sliding Window')..."
            value={query}
            onChange={e => setQuery(e.target.value)}
            className="w-full bg-transparent border-none outline-hidden text-sm text-[#E5E7EB] placeholder-[#64748B] font-mono"
            onKeyDown={e => {
              if (e.key === 'Escape') onClose();
            }}
          />
          <button
            onClick={onClose}
            aria-label="Close command palette"
            className="p-1 rounded text-[#94A3B8] hover:text-white hover:bg-[#1E293B] focus-ring"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Results List */}
        <div className="max-h-[60vh] overflow-y-auto p-2 space-y-3 font-mono text-xs">
          {isValidDay && (
            <div>
              <div className="px-2 py-1 text-[10px] text-[#64748B] uppercase tracking-wider font-semibold">
                JUMP TO DAY
              </div>
              <button
                onClick={() => handleJumpDay(matchedDay!)}
                className="w-full flex items-center justify-between p-2 rounded bg-[#38BDF8]/10 hover:bg-[#38BDF8]/20 border border-[#38BDF8]/30 text-[#38BDF8] text-left"
              >
                <span>Switch active workspace to Day {matchedDay} / 180</span>
                <ArrowRight className="w-4 h-4" />
              </button>
            </div>
          )}

          {filteredCommands.length > 0 && (
            <div>
              <div className="px-2 py-1 text-[10px] text-[#64748B] uppercase tracking-wider font-semibold">
                SYSTEM COMMANDS & VIEWS
              </div>
              <div className="space-y-0.5">
                {filteredCommands.map(cmd => {
                  const Icon = cmd.icon;
                  return (
                    <button
                      key={cmd.id}
                      onClick={() => handleSelect(cmd.view)}
                      className="w-full flex items-center justify-between p-2 rounded hover:bg-[#1E293B] text-[#94A3B8] hover:text-white text-left transition-colors"
                    >
                      <div className="flex items-center gap-2.5">
                        <Icon className="w-4 h-4 text-[#38BDF8]" />
                        <span className="text-white font-medium">{cmd.label}</span>
                      </div>
                      <span className="text-[10px] text-[#64748B] px-1.5 py-0.5 rounded bg-[#0B0E14] border border-[#1E293B]">
                        {cmd.category}
                      </span>
                    </button>
                  );
                })}
              </div>
            </div>
          )}

          {filteredTopics.length > 0 && (
            <div>
              <div className="px-2 py-1 text-[10px] text-[#64748B] uppercase tracking-wider font-semibold">
                KNOWLEDGE TOPICS
              </div>
              <div className="space-y-0.5">
                {filteredTopics.map(topic => (
                  <button
                    key={topic.id}
                    onClick={() => handleSelect('knowledge')}
                    className="w-full flex items-center justify-between p-2 rounded hover:bg-[#1E293B] text-left transition-colors"
                  >
                    <div>
                      <div className="text-white font-medium">{topic.title}</div>
                      <div className="text-[10px] text-[#94A3B8]">{topic.category} · {topic.difficulty}</div>
                    </div>
                    <span className="text-[10px] text-[#22C55E] font-semibold">{topic.status}</span>
                  </button>
                ))}
              </div>
            </div>
          )}

          {filteredDSA.length > 0 && (
            <div>
              <div className="px-2 py-1 text-[10px] text-[#64748B] uppercase tracking-wider font-semibold">
                DSA PROBLEMS
              </div>
              <div className="space-y-0.5">
                {filteredDSA.map(p => (
                  <button
                    key={p.id}
                    onClick={() => handleSelect('dsa')}
                    className="w-full flex items-center justify-between p-2 rounded hover:bg-[#1E293B] text-left transition-colors"
                  >
                    <div>
                      <div className="text-white font-medium">{p.title}</div>
                      <div className="text-[10px] text-[#94A3B8]">{p.pattern} · {p.difficulty}</div>
                    </div>
                    <span className="text-[10px] text-[#38BDF8]">Java O({p.timeComplexity})</span>
                  </button>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

// src/vue/components/CommandPalette.vue
<script setup lang="ts">
import { computed, ref, onMounted, onBeforeUnmount, nextTick } from 'vue';
import { useRouter } from 'vue-router';
import { Search, CornerDownLeft } from 'lucide-vue-next';

const emit = defineEmits<{ close: [] }>();
const router = useRouter();

interface Command {
  label: string;
  to: string;
  section: string;
}

/** Only routes that actually exist in the canonical route table. */
const commands: Command[] = [
  { label: 'Go to Command Center', to: '/', section: 'Navigation' },
  { label: 'Go to Roadmap', to: '/learning/roadmap', section: 'Learning' },
  { label: 'Go to Learning Path', to: '/learning', section: 'Navigation' },
  { label: 'Go to Java 25', to: '/learning/java', section: 'Learning' },
  { label: 'Go to AI Knowledge', to: '/learning/ai', section: 'Learning' },
  { label: 'Go to Technical English', to: '/english', section: 'Learning' },
  { label: 'Go to Spring Boot', to: '/learning/spring', section: 'Learning' },
  { label: 'Go to Microservices Track', to: '/learning/microservices', section: 'Learning' },
  { label: 'Go to Engineering Judgment Lab', to: '/engineering/judgment', section: 'Engineering' },
  { label: 'Go to Architecture', to: '/architecture', section: 'Navigation' },
  { label: 'Go to AWS AIF-C01', to: '/certifications/aws/aif-c01', section: 'Certifications' },
  {
    label: 'Go to Senior Engineering Certification',
    to: '/certifications/senior-engineering',
    section: 'Certifications',
  },
  { label: 'Go to Interview', to: '/interview', section: 'Navigation' },
  { label: 'Go to Mistakes', to: '/review/mistakes', section: 'Review' },
  { label: 'Go to Settings', to: '/settings', section: 'Configuration' },
];

const query = ref('');
const activeIndex = ref(0);
const listRef = ref<HTMLElement | null>(null);
const inputRef = ref<HTMLInputElement | null>(null);

const filtered = computed<Command[]>(() => {
  const q = query.value.trim().toLowerCase();
  if (!q) return commands;
  return commands.filter(
    (c) => c.label.toLowerCase().includes(q) || c.section.toLowerCase().includes(q),
  );
});

function move(delta: number): void {
  if (filtered.value.length === 0) return;
  activeIndex.value = (activeIndex.value + delta + filtered.value.length) % filtered.value.length;
  nextTick(() => {
    const items = listRef.value?.querySelectorAll('[data-command]');
    const target = items ? items[activeIndex.value] : undefined;
    // jsdom (and some embedded browsers) do not implement scrollIntoView
    if (typeof target?.scrollIntoView === 'function') {
      target.scrollIntoView({ block: 'nearest' });
    }
  });
}

function run(command: Command | undefined): void {
  if (!command) return;
  emit('close');
  void router.push(command.to);
}

function onKeydown(e: KeyboardEvent): void {
  if (e.key === 'ArrowDown') {
    e.preventDefault();
    move(1);
  } else if (e.key === 'ArrowUp') {
    e.preventDefault();
    move(-1);
  } else if (e.key === 'Enter') {
    e.preventDefault();
    run(filtered.value[activeIndex.value]);
  }
}

onMounted(() => inputRef.value?.focus());
onBeforeUnmount(() => {
  // focus restore target is the TopBar search trigger (semantic, always present)
  document.querySelector<HTMLButtonElement>('[aria-label="Open command palette"]')?.focus();
});
</script>

<template>
  <div
    class="fixed inset-0 z-[60] flex items-start justify-center pt-[12vh] bg-black/70"
    role="dialog"
    aria-modal="true"
    aria-label="Command palette"
    @click.self="emit('close')"
  >
    <div
      class="w-full max-w-lg rounded-lg border border-[#1E293B] bg-[#111622] shadow-2xl overflow-hidden"
      data-testid="command-palette"
    >
      <div class="flex items-center gap-2 px-3 py-2.5 border-b border-[#1E293B]">
        <Search class="w-4 h-4 text-[#64748B]" aria-hidden="true" />
        <input
          ref="inputRef"
          v-model="query"
          type="text"
          role="combobox"
          aria-expanded="true"
          aria-controls="command-list"
          aria-activedescendant="command-option-0"
          placeholder="Type a command…"
          class="flex-1 bg-transparent text-sm text-[#E5E7EB] placeholder-[#475569] outline-none"
          @input="activeIndex = 0"
          @keydown="onKeydown"
        />
        <kbd class="text-[9px] font-mono text-[#475569] border border-[#1E293B] rounded px-1 py-0.5">Esc</kbd>
      </div>

      <div v-if="filtered.length === 0" class="px-4 py-8 text-center text-xs font-mono text-[#64748B]">
        Search is not available yet — only route navigation commands exist.
      </div>

      <ul
        v-else
        id="command-list"
        ref="listRef"
        role="listbox"
        aria-label="Commands"
        class="max-h-72 overflow-y-auto custom-scrollbar py-1"
      >
        <li
          v-for="(command, index) in filtered"
          :id="`command-option-${index}`"
          :key="command.to + command.label"
          role="option"
          :aria-selected="index === activeIndex"
          data-command
          class="flex items-center justify-between px-3 py-2 text-sm cursor-pointer"
          :class="index === activeIndex ? 'bg-[#1E293B] text-white' : 'text-[#94A3B8]'"
          @mouseenter="activeIndex = index"
          @click="run(command)"
        >
          <span class="flex items-center gap-2.5">
            <CornerDownLeft v-if="index === activeIndex" class="w-3 h-3 text-[#38BDF8]" aria-hidden="true" />
            <span class="font-medium">{{ command.label }}</span>
          </span>
          <span class="text-[10px] font-mono px-1.5 py-0.5 rounded border border-[#1E293B] bg-[#0B0E14] text-[#64748B]">
            {{ command.section }}
          </span>
        </li>
      </ul>
    </div>
  </div>
</template>

<style scoped>
@media (prefers-reduced-motion: no-preference) {
  [data-command] {
    transition: background-color 0.1s ease;
  }
}
</style>
